FROM rancher/os-installer

ARG VERSION
ARG KERNEL_VERSION
ENV VERSION=${VERSION}
ENV KERNEL_VERSION=${KERNEL_VERSION}

# TODO: separate out the 3 elements below - so we can mix and match updates
RUN rm /dist/ \
    && mkdir -p /dist/
COPY ./build/vmlinuz-${KERNEL_VERSION} ./build/initrd ./build/ros /dist/

