// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "617f18b-dirty"
	VERSION   string = "1.5.0-dev"

	IAMSTATIC string = "true"
	INITSHA1  string = ""
	INITPATH  string = ""
)
