#!/bin/bash
set -e

cd $(dirname $0)/..

: ${ARTIFACTS:=$(pwd)/assets}
: ${BUILD:=$(pwd)/build}
: ${CONFIG:=$(pwd)/config}
: ${DIST:=$(pwd)/dist}

mkdir -p ${BUILD} ${DIST}

busybox_install()
{
    local conf=$1
    local bbconf=$2
    local target=$3

    if [ "$#" = "2" ]; then
        target=$2
        bbconf=
    fi

    cd ${BUILD}

    local buildroot=$(ls -1 ${ARTIFACTS}/buildroot-*.tar.bz2)

    if [ ! -e "${buildroot}" ]; then
        echo "Failed to find busybox archive, found : ${buildroot}" 1>&2
        return 1
    else
        buildroot=$(basename $buildroot)
    fi

    if [ ! -e ${buildroot/.tar.bz2//} ]; then
        tar xvjf ${ARTIFACTS}/${buildroot}
    fi

    cd ${buildroot/.tar.bz2//}

    cp $conf .config
    if [ -n "$bbconf" ]; then
        cp $bbconf package/busybox/
    fi
    make oldconfig
    make
}

busybox_install ${CONFIG}/buildroot-config-static ${CONFIG}/busybox-ps-modprobe-only.config ${DIST}/rootfs-static.tar
