#!/bin/bash
set -e
set -x

cd $(dirname $0)/..

apt-get update
apt-get install -y curl rsync build-essential syslinux xorriso libblkid-dev libmount-dev libselinux1-dev

if [ ! -d /usr/local/go ]; then
    curl -sL https://storage.googleapis.com/golang/go1.4.1.linux-amd64.tar.gz | tar xvzf - -C /usr/local
fi
