#!/bin/bash
set -e

cd $(dirname $0)/..

source scripts/build-common
source scripts/version

>${BUILD}/tags
for i in scripts/extraimages/[0-9]*; do
    tag=$(echo $i | cut -f2 -d-):${VERSION}
    echo Building $tag
    docker build -t rancher/$tag -f $i .
    echo $tag >> ${BUILD}/tags
done
