#!/bin/bash
set -e

ros="$1"

source $(dirname $0)/version

cd $(dirname $0)/..

if [ "${!TOOLCHAIN}" != "" ]; then
  export CC=/usr/bin/${!TOOLCHAIN}-gcc
  export CGO_ENABLED=1
fi

OUTPUT=${OUTPUT:-bin/ros}
echo Building $OUTPUT

CONST="-X github.com/docker/docker/dockerversion.GitCommit=${COMMIT} -X github.com/docker/docker/dockerversion.Version=${DOCKER_PATCH_VERSION} -X github.com/docker/docker/dockerversion.BuildTime=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -X github.com/docker/docker/dockerversion.IAmStatic=true -X github.com/rancher/os/config.VERSION=${VERSION} -X github.com/rancher/os/config.OS_REPO=${OS_REPO}"
go build -tags "selinux cgo daemon netgo dnspatch" -installsuffix netgo -ldflags "$CONST -linkmode external -extldflags -static -s -w" -o ${OUTPUT}
