#!/bin/bash
set -ex

ros="$1"

source $(dirname $0)/version

cd $(dirname $0)/..

if [ "${!TOOLCHAIN}" != "" ]; then
  export CC=/usr/bin/${!TOOLCHAIN}-gcc
  export CGO_ENABLED=1
fi

OUTPUT=${OUTPUT:-bin/ros}
echo Building $OUTPUT
BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

CONST="-X github.com/rancher/os/config.Version=${VERSION} -X github.com/rancher/os/config.OsRepo=${OS_REPO} -X github.com/rancher/os/config.BuildDate='${BUILDDATE}'"
go build -tags "selinux cgo daemon netgo" -installsuffix netgo -ldflags "$CONST -linkmode external -extldflags -static -s -w" -o ${OUTPUT}
