#!/bin/bash
set -e

cd $(dirname $0)/..

source scripts/build-common

>${BUILD}/tags
for i in scripts/extraimages/[0-9]*; do
    tag=$(echo $i | cut -f2 -d-)
    echo Building $tag
    docker build -t rancher/$tag -f $i .
    echo $tag >> ${BUILD}/tags
done
