#!/bin/bash
set -ex

cd $(dirname $0)/..

source ./scripts/version

CHECKSUM="dist/checksums.txt"
rm -f $CHECKSUM

FILELIST="
burmillaos-${VERSION}.iso
burmillaos-${VERSION}-aliyun.vhd
burmillaos-${VERSION}-cloudstack.img
burmillaos-${VERSION}-digitalocean.img
burmillaos-${VERSION}-openstack.img
burmillaos-${VERSION}-gce.tar.gz
burmillaos-${VERSION}-raspberry-pi64.zip
burmillaos-${VERSION}-4glte.iso
burmillaos-${VERSION}-hyperv.iso
burmillaos-${VERSION}-proxmoxve.iso
burmillaos-${VERSION}-vmware.iso
"

rm -rf dist/checksums && mkdir -p dist/checksums
pushd dist/checksums
for file in $FILELIST; do
    curl -sSL -o $file https://github.com/burmilla/os/releases/download/$VERSION/$file
    for algo in sha256 md5; do
        echo "$algo: $(${algo}sum $file)" >> ../../$CHECKSUM
    done
done
popd

echo "github-release upload --user burmilla --repo os --tag ${VERSION} --file $CHECKSUM --name checksums.txt"
#echo "gsutil cp $CHECKSUM gs://releases.rancher.com/os/latest/checksums.txt"
#echo "gsutil cp $CHECKSUM gs://releases.rancher.com/os/$VERSION/checksums.txt"
