#!/bin/bash
set -ex

cd $(dirname $0)/..

if [ -x "$(which wrapdocker)" ] && ! docker info >/dev/null 2>&1; then
    wrapdocker
fi

docker build -t ros-build-base -f Dockerfile.build-base .
docker build -t ros-build -f Dockerfile.build .
./scripts/docker-run.sh --name ros-ci make -f Makefile.docker DEV_BUILD=1 minimal integration-tests
