#!/bin/bash
set -e

cd $(dirname $0)/..

echo BUILD
./scripts/build
echo TEST
./scripts/test
echo VALIDATE
./scripts/validate
echo PREPARE
./scripts/prepare
echo PACKAGE
./scripts/package
echo INTEGRATION-TEST
./scripts/integration-test

