#!/bin/bash
set -e

cd $(dirname $0)/..
rm -rf build dist bin images/*/build state
rm -rf ./scripts/images/openstack/dist

docker rmi $(docker images --format "{{.Repository}}:{{.Tag}}" | grep rancher) || true
docker rmi $(docker images --filter dangling=true -q) ||true
