#!/bin/bash
set -ex

cd $(dirname $0)/..

. scripts/build-common
. scripts/version

VERSION=${VERSION:?"VERSION not set"}
BUILD=${BUILD:?"BUILD not set"}


CONTAINER_KERNEL=$(docker create rancher/os-kernel:${VERSION})
cleanup_kernel() {
    docker rm -v ${CONTAINER_KERNEL}
}
trap cleanup_kernel EXIT

docker cp ${CONTAINER_KERNEL}:/kernel ${BUILD} # copies files to ${BUILD}/kernel
