#!/bin/bash
# help: For development, creates iso, kernel, initrd gzip compressed
set -e

cd $(dirname $0)

echo ------------------------ ./build
./build
echo ------------------------ ./prepare
./prepare
echo ------------------------ ./package
ROOTFS=0 ./package
