#!/bin/bash
set -ex

cd $(dirname $0)/..


source ./scripts/version
./scripts/release

ISO_NAME="rancheros-autoformat.iso"

mkdir -p /tmp/dist && mv ./dist/* /tmp/dist/
mkdir -p ./dist/hyperv && mv /tmp/dist/* ./dist/hyperv/
mkdir -p ./dist/artifacts && cp ./dist/hyperv/artifacts/rancheros.iso ./dist/artifacts/${ISO_NAME}
echo "gsutil cp dist/artifacts/${ISO_NAME} gs://releases.rancher.com/os/latest/hyperv/${ISO_NAME}"
echo "gsutil cp dist/artifacts/${ISO_NAME} gs://releases.rancher.com/os/${VERSION}/hyperv/${ISO_NAME}"
