#!/bin/bash
# help: Run integration tests
set -e

if [ "$INTEGRATION_TESTS" = 0 ]; then
    exit 0
fi

source $(dirname $0)/version

cd $(dirname $0)/../tests

if [ ! -e "../dist/artifacts/$INITRD" ]; then
    ../scripts/dev
fi

if [ "$RUNTEST" != "" ]; then
	RUNTEST="-check.f ${RUNTEST}"
fi

time go test -v -timeout 9999m $RUNTEST
