#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)

if [ ! -e ./bin/host_ros ]; then
    ./build
fi

./template
if [ "$HOST_ARCH" = "$ARCH" ]; then
    CORE=true ./build-images
fi
./tar-images
./layout
