#!/bin/bash
set -ex

cd $(dirname $0)/..

source ./scripts/version

if [ ! -f ./dist/artifacts/rootfs_arm64.tar.gz ]; then
    echo "Please run make first"
    exit 0
fi

cp ./dist/artifacts/rootfs_arm64.tar.gz ./scripts/images/raspberry-pi-hypriot64/
pushd ./scripts/images/raspberry-pi-hypriot64/
./../../../.dapper
popd

cp ./scripts/images/raspberry-pi-hypriot64/dist/burmillaos-raspberry-pi64.zip ./dist/artifacts/

touch dist/publish.sh
chmod 755 dist/publish.sh

echo "github-release upload --user burmilla --repo os --tag ${VERSION} --file dist/artifacts/burmillaos-raspberry-pi64.zip --name burmillaos-${VERSION}-raspberry-pi64.zip" >> dist/publish.sh
