#!/bin/bash
set -ex

cd $(dirname $0)/..

touch .make-proxmoxve

source ./scripts/version
./scripts/release-build

touch dist/publish.sh
chmod 755 dist/publish.sh

echo "github-release upload --user burmilla --repo os --tag ${VERSION} --file dist/artifacts/burmillaos.iso --name burmillaos-${VERSION}-proxmoxve.iso" > dist/publish.sh
