#!/bin/bash

cd $(dirname $0)/../dist/moby

if [ "1" == "2" ]; then
  linuxkit run -mem 4096 -gui rancheros
else

	CMDLINE="$(cat ./rancheros-cmdline)"

	   # DISPLAY_OPTS="${DISPLAY_OPTS} -serial tcp::4444,server"
	   # KERNEL_ARGS="rancher.console=ttyS1 rancher.autologin=ttyS1 ${KERNEL_ARGS}"
#	-monitor telnet:127.0.0.1:1234,server,nowait \
#        -curses \
#	-serial tcp::4444,server \
  qemu-system-x86_64 \
	-nographic \
	-kernel ./rancheros-kernel \
	-initrd ./rancheros-initrd.img \
	-m 4096 \
  -device virtio-rng-pci \
  -smp 1 \
  -enable-kvm \
  -machine q35,accel=kvm:tcg \
	-net nic,vlan=0,model=virtio \
	-net user,vlan=0,hostfwd=tcp::3333-:22,hostname=rancher-moby \
	-append "$CMDLINE"
fi
