#!/bin/bash
set -x -e

vboxnet=vboxnet1
ip_prefix=172.17.7

## DOC: configure VirtualBox ${vboxnet} host-only virtual network for use with a RancherOS VM cluster

## NOTE: host-only NIC ${vboxnet} should already exist!

vboxmanage hostonlyif ipconfig ${vboxnet} --ip ${ip_prefix}.1
vboxmanage dhcpserver remove --ifname ${vboxnet} && :
vboxmanage dhcpserver add --ifname ${vboxnet} --ip ${ip_prefix}.100 --netmask 255.255.255.0 \
    --lowerip ${ip_prefix}.101 --upperip ${ip_prefix}.254 --enable
