FROM golang:1.4.2-cross

RUN go get github.com/mitchellh/gox
RUN go get github.com/tools/godep

ENV GOPATH /go/src/github.com/rancher/docker-from-scratch/Godeps/_workspace:/go

WORKDIR /go/src/github.com/rancher/docker-from-scratch
